version: "3.8"

services:
  frontend:
    container_name: frontend
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/frontend-ms
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - PORT=3000
      - SERVICE_BACKEND1=http://localhost:18010/api/message
    ports:
      - "18000:3000"
    networks:
      - net-app-front-back

  backend1:
    container_name: backend1
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/backend1-ms
    build:
      context: .
      dockerfile: backend1/Dockerfile
    environment:
      - PORT=3010
      - SERVICE_BACKEND2=http://backend2:3020/api/message
    ports:
      - "18010:3010"
    networks:
      - net-app-front-back
      - net-app-back-back

  backend2:
    container_name: backend2
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/backend2-ms
    build:
      context: .
      dockerfile: backend2/Dockerfile
    environment:
      - PORT=3020
    networks:
      - net-app-back-back

networks:
  net-app-front-back:
    driver: bridge
  net-app-back-back:
    driver: bridge
