apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  containers:
    - name: web
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-jenkins
spec:
  containers:
    - name: devops
      image: jenkins/jenkins
